if(SICT_USE_SHARED)
  message(STATUS "Use sict in shared library")
  include(cmake/sict-shared.cmake)
  add_library(sict INTERFACE)
  target_link_libraries(sict INTERFACE sict_shared_impl)
else()
  message(STATUS "Use sict in static library")
  include(cmake/sict-static.cmake)
  add_library(sict INTERFACE)
  target_link_libraries(sict INTERFACE sict_static_impl)
endif()
